#!/usr/bin/env python3
"""Build the Typhoon-vs-Claude comparison artifact per eval.

For each Typhoon draft in the target iteration, finds the most-recent Claude
`with_skill` output (the kode-thai loop) for the same eval — across all
iterations, since the two arms may not be co-generated — and writes a
comparison.md: a mechanical-signal table + both prose blocks side by side.

The signals are advisory (forbidden-phrase hits, connective density, exclamation
count, length). They route chakrit's ear; they are NOT a quality verdict.

Run: uv run python tests/generate/compare_arms.py [iteration-N]
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from lib import WORKSPACE, latest_iteration, mechanical_signals  # noqa: E402


def most_recent_claude(eval_name: str) -> Path | None:
    """Highest-numbered iteration with a NON-EMPTY claude/with_skill output.

    Empty outputs exist (failed/timed-out generations, e.g. iter-7 marketing is
    0 bytes) — skip them so the comparison falls back to the last real one.
    """
    candidates = WORKSPACE.glob(f"iteration-*/{eval_name}/claude/with_skill/output.md")
    found = [
        (int(p.parents[3].name.split("-")[1]), p)
        for p in candidates
        if p.read_text(encoding="utf-8").strip()
    ]
    return max(found)[1] if found else None


def signal_row(label: str, sig: dict) -> str:
    forb = ", ".join(sig["forbidden_hits"]) if sig["forbidden_hits"] else "—"
    return (
        f"| {label:<16} | {sig['chars']:>5} | {sig['paragraphs']:>3} | "
        f"{sig['connective_density']:>4} | {sig['exclamations']:>3} | {forb} |"
    )


def build(iteration: Path) -> list[str]:
    written: list[str] = []
    for typ_out in sorted(iteration.glob("*/typhoon/draft/output.md")):
        eval_name = typ_out.parents[2].name
        typ_text = typ_out.read_text(encoding="utf-8")
        claude_path = most_recent_claude(eval_name)
        claude_text = claude_path.read_text(encoding="utf-8") if claude_path else ""

        typ_sig = mechanical_signals(typ_text)
        rows = [signal_row("typhoon-draft", typ_sig)]
        if claude_path:
            rows.append(signal_row("claude+skill", mechanical_signals(claude_text)))
        claude_src = (
            str(claude_path.relative_to(WORKSPACE.parent))
            if claude_path
            else "NONE — no Claude with_skill output exists for this eval yet"
        )

        md = [
            f"# Comparison: {eval_name}",
            "",
            "<!-- Generated by compare_arms.py. Mechanical signals are advisory — "
            "they route the ear, not a verdict. -->",
            "",
            f"- **Typhoon draft:** `{typ_out.relative_to(WORKSPACE.parent)}`",
            f"- **Claude + skill:** `{claude_src}`",
            "  (NOT co-generated — most-recent existing output; rerun for a clean pair)"
            if claude_path else "",
            "",
            "## Mechanical signals",
            "",
            "| arm              | chars | par | c/1k | `!` | forbidden hits |",
            "| ---------------- | ----: | --: | ---: | --: | -------------- |",
            *rows,
            "",
            "## Typhoon draft (native, un-audited)",
            "",
            typ_text.strip(),
            "",
            "## Claude + kien-thai skill (kode-thai loop)",
            "",
            claude_text.strip() if claude_path else "_(no Claude output yet)_",
            "",
        ]
        dest = typ_out.parents[2] / "comparison.md"
        dest.write_text("\n".join(line for line in md if line is not None) + "\n", encoding="utf-8")
        written.append(str(dest.relative_to(WORKSPACE.parent)))
    return written


def main() -> None:
    if len(sys.argv) > 1:
        iteration = WORKSPACE / sys.argv[1]
        if not iteration.is_dir():
            raise SystemExit(f"no such iteration: {iteration}")
    else:
        iteration = latest_iteration()
        if iteration is None:
            raise SystemExit("no iterations in workspace")
    written = build(iteration)
    if not written:
        print(f"no typhoon drafts found in {iteration.name}")
        return
    print(f"wrote {len(written)} comparison(s):")
    for w in written:
        print(f"  {w}")


if __name__ == "__main__":
    main()
