#!/usr/bin/env python3
"""Build the Typhoon-vs-Claude comparison artifact per eval.

For each Typhoon draft in the target iteration, finds the Claude `with_skill`
output (the kode-thai loop) to pair it with — the same iteration when the run was
co-generated, the newest one anywhere otherwise — and writes a comparison.md: a
mechanical-signal table + both prose blocks side by side. A pair that is not
co-generated says so, since it does not isolate the drafter.

The signals are advisory (forbidden-phrase hits, connective density, exclamation
count, length). They route chakrit's ear; they are NOT a quality verdict.

Run: uv run python tests/generate/compare_arms.py [iteration-N]
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from lib import (  # noqa: E402
    WORKSPACE,
    ArmRef,
    Signals,
    claude_arm,
    latest_iteration,
    mechanical_signals,
)


def signal_row(label: str, sig: Signals) -> str:
    forbidden = ", ".join(sig.forbidden_hits) if sig.forbidden_hits else "—"
    return (
        f"| {label:<16} | {sig.chars:>5} | {sig.paragraphs:>3} | "
        f"{sig.connective_density:>4} | {sig.exclamations:>3} | {forbidden} |"
    )


def _rel(path: Path) -> str:
    return str(path.relative_to(WORKSPACE.parent))


def _source_lines(typ_out: Path, arm: ArmRef | None) -> list[str]:
    if arm is None:
        return [
            f"- **Typhoon draft:** `{_rel(typ_out)}`",
            "- **Claude + skill:** NONE — no with_skill output for this eval yet",
        ]
    provenance = (
        "  (co-generated — same iteration, same skill state; the pair isolates the drafter)"
        if arm.co_generated
        else "  (NOT co-generated — most-recent existing output; rerun for a clean pair)"
    )
    return [
        f"- **Typhoon draft:** `{_rel(typ_out)}`",
        f"- **Claude + skill:** `{_rel(arm.path)}`",
        provenance,
    ]


def render_comparison(typ_out: Path) -> str:
    """Markdown for one eval: source header, signal table, both prose blocks."""
    eval_name = typ_out.parents[2].name
    typ_text = typ_out.read_text(encoding="utf-8")
    arm = claude_arm(eval_name, typ_out.parents[3])
    claude_text = arm.path.read_text(encoding="utf-8") if arm else ""

    rows = [signal_row("typhoon-draft", mechanical_signals(typ_text))]
    if arm:
        rows.append(signal_row("claude+skill", mechanical_signals(claude_text)))
    claude_block = claude_text.strip() if arm else "_(no Claude output yet)_"

    sections = [
        f"# Comparison: {eval_name}",
        "",
        "<!-- Generated by compare_arms.py. Mechanical signals are advisory — "
        "they route the ear, not a verdict. -->",
        "",
        *_source_lines(typ_out, claude_path),
        "",
        "## Mechanical signals",
        "",
        "| arm              | chars | par | c/1k | `!` | forbidden hits |",
        "| ---------------- | ----: | --: | ---: | --: | -------------- |",
        *rows,
        "",
        "## Typhoon draft (native, un-audited)",
        "",
        typ_text.strip(),
        "",
        "## Claude + kien-thai skill (kode-thai loop)",
        "",
        claude_block,
        "",
    ]
    return "\n".join(sections) + "\n"


def build(iteration: Path) -> list[str]:
    written: list[str] = []
    for typ_out in sorted(iteration.glob("*/typhoon/draft/output.md")):
        dest = typ_out.parents[2] / "comparison.md"
        dest.write_text(render_comparison(typ_out), encoding="utf-8")
        written.append(str(dest.relative_to(WORKSPACE.parent)))
    return written


def main() -> None:
    if len(sys.argv) > 1:
        iteration = WORKSPACE / sys.argv[1]
        if not iteration.is_dir():
            raise SystemExit(f"no such iteration: {iteration}")
    else:
        iteration = latest_iteration()
        if iteration is None:
            raise SystemExit("no iterations in workspace")
    written = build(iteration)
    if not written:
        print(f"no typhoon drafts found in {iteration.name}")
        return
    print(f"wrote {len(written)} comparison(s):")
    for w in written:
        print(f"  {w}")


if __name__ == "__main__":
    main()
